/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { ActionStep } from './actionStep';
import type { AutonomyEligibility } from './autonomyEligibility';
import type { ProposalStatus } from './proposalStatus';
import type { RiskLevel } from './riskLevel';

export interface ActionProposal {
  id: string;
  incident_id: string;
  title: string;
  summary: string;
  overall_risk: RiskLevel;
  estimated_impact: string;
  status: ProposalStatus;
  autonomy_eligibility: AutonomyEligibility;
  /** @minItems 1 */
  steps: ActionStep[];
  created_at: string;
  updated_at: string;
}
