/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */

export type ArticleProcessingState = typeof ArticleProcessingState[keyof typeof ArticleProcessingState];


export const ArticleProcessingState = {
  raw: 'raw',
  enriched: 'enriched',
  irrelevant: 'irrelevant',
  evaluated: 'evaluated',
  proposal_generated: 'proposal_generated',
} as const;
