/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleProcessingState } from './articleProcessingState';

export interface Article {
  id: string;
  source: string;
  source_url: string;
  headline: string;
  title: string;
  summary: string;
  preview_text: string;
  analysis: string;
  keywords: string[];
  tags: string[];
  source_name: string;
  body: string;
  published_at: string;
  publish_datetime: string;
  /** @nullable */
  preview_image_url: string | null;
  ingestion_run_id: string;
  processing_state: ArticleProcessingState;
  created_at: string;
  updated_at: string;
}
