/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */

export type AutonomyIneligibilityReason = typeof AutonomyIneligibilityReason[keyof typeof AutonomyIneligibilityReason];


export const AutonomyIneligibilityReason = {
  risk_above_company_threshold: 'risk_above_company_threshold',
  blocked_category: 'blocked_category',
  autonomy_disabled: 'autonomy_disabled',
  eligible: 'eligible',
} as const;
