/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { MasterStatus } from './masterStatus';
import type { SkuRiskLevel } from './skuRiskLevel';

export interface CreateSkuRequest {
  sku_code: string;
  name: string;
  description: string;
  unit_of_measure: string;
  status: MasterStatus;
  /**
   * @minimum 0
   * @maximum 100
   */
  risk_score: number;
  risk_level: SkuRiskLevel;
  category: string;
  supplier_ids: string[];
}
