/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { EnrichmentHorizon } from './enrichmentHorizon';
import type { GeoInfo } from './geoInfo';
import type { ImpactWindow } from './impactWindow';
import type { MatchedEntities } from './matchedEntities';
import type { RelevanceTag } from './relevanceTag';
import type { RiskLevel } from './riskLevel';

export interface Enrichment {
  article_id: string;
  is_relevant: boolean;
  relevance_tags: RelevanceTag[];
  horizon: EnrichmentHorizon;
  geo: GeoInfo;
  impact_window: ImpactWindow;
  matched_entities: MatchedEntities;
  /**
   * @minimum 0
   * @maximum 100
   */
  risk_score: number;
  risk_level: RiskLevel;
  explanation: string;
}
