/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { Incident } from './incident';

export interface IncidentListResponse {
  items: Incident[];
  /** @minimum 0 */
  total: number;
  /** @minimum 1 */
  page: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  page_size: number;
}
