/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { IncidentClassification } from './incidentClassification';
import type { IncidentStatus } from './incidentStatus';
import type { OverlapTag } from './overlapTag';
import type { RiskLevel } from './riskLevel';

export interface Incident {
  id: string;
  article_id: string;
  classification: IncidentClassification;
  status: IncidentStatus;
  reasoning: string;
  overlap_tags: OverlapTag[];
  /**
   * @minimum -1
   * @maximum 100
   */
  risk_score: number;
  risk_level: RiskLevel;
  created_at: string;
  updated_at: string;
}
