/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */

export interface IngestionStats {
  /** @minimum 0 */
  articles_ingested: number;
  /** @minimum 0 */
  articles_relevant: number;
  /** @minimum 0 */
  incidents_created: number;
  /** @minimum 0 */
  proposals_generated: number;
}
