/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { IngestionRunStatus } from './ingestionRunStatus';
import type { IngestionStats } from './ingestionStats';

export interface IngestionRun {
  id: string;
  status: IngestionRunStatus;
  started_at: string;
  /** @nullable */
  finished_at?: string | null;
  created_at: string;
  stats: IngestionStats;
  /** @nullable */
  error?: string | null;
}
