/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleProcessingState } from './articleProcessingState';
import type { ArticleStateParameter } from './articleStateParameter';
import type { PageParameter } from './pageParameter';
import type { PageSizeParameter } from './pageSizeParameter';
import type { RelevantParameter } from './relevantParameter';

export type ListArticlesParams = {
state?: ArticleStateParameter;
relevant?: RelevantParameter;
/**
 * @minimum 1
 */
page?: PageParameter;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: PageSizeParameter;
};
