/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */

export type OverlapTag = typeof OverlapTag[keyof typeof OverlapTag];


export const OverlapTag = {
  port_overlap: 'port_overlap',
  route_overlap: 'route_overlap',
  immediate_sku_threat: 'immediate_sku_threat',
} as const;
