/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { ProposalFeedbackResponseStatus } from './proposalFeedbackResponseStatus';
import type { RiskProfile } from './riskProfile';

export interface ProposalFeedbackResponse {
  status: ProposalFeedbackResponseStatus;
  risk_profile: RiskProfile;
}
