/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */

export type SkuRiskLevel = typeof SkuRiskLevel[keyof typeof SkuRiskLevel];


export const SkuRiskLevel = {
  critical: 'critical',
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;
