/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type { ShipmentEvent } from './shipmentEvent';
import type { ShipmentStatus } from './shipmentStatus';
import type { UpdateShipmentRequestSkus } from './updateShipmentRequestSkus';

export interface UpdateShipmentRequest {
  shipment_code?: string;
  status?: ShipmentStatus;
  origin_port_id?: string;
  destination_port_id?: string;
  route_id?: string;
  supplier_id?: string;
  /** Map of sku_id to quantity required */
  skus?: UpdateShipmentRequestSkus;
  carrier?: string;
  order_date?: string;
  expected_delivery_date?: string;
  events?: ShipmentEvent[];
}
