/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List ingestion runs
 */
export const listIngestionRunsQueryPageDefault = 1;

export const listIngestionRunsQueryPageSizeDefault = 20;
export const listIngestionRunsQueryPageSizeMax = 100;



export const ListIngestionRunsQueryParams = zod.object({
  "page": zod.number().min(1).default(listIngestionRunsQueryPageDefault),
  "page_size": zod.number().min(1).max(listIngestionRunsQueryPageSizeMax).default(listIngestionRunsQueryPageSizeDefault)
})

export const listIngestionRunsResponseItemsItemStatsArticlesIngestedMin = 0;

export const listIngestionRunsResponseItemsItemStatsArticlesRelevantMin = 0;

export const listIngestionRunsResponseItemsItemStatsIncidentsCreatedMin = 0;

export const listIngestionRunsResponseItemsItemStatsProposalsGeneratedMin = 0;

export const listIngestionRunsResponseTotalMin = 0;


export const listIngestionRunsResponsePageSizeMax = 100;



export const ListIngestionRunsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "status": zod.enum(['queued', 'running', 'completed', 'failed']),
  "started_at": zod.string().datetime({}),
  "finished_at": zod.string().datetime({}).nullish(),
  "created_at": zod.string().datetime({}),
  "stats": zod.object({
  "articles_ingested": zod.number().min(listIngestionRunsResponseItemsItemStatsArticlesIngestedMin),
  "articles_relevant": zod.number().min(listIngestionRunsResponseItemsItemStatsArticlesRelevantMin),
  "incidents_created": zod.number().min(listIngestionRunsResponseItemsItemStatsIncidentsCreatedMin),
  "proposals_generated": zod.number().min(listIngestionRunsResponseItemsItemStatsProposalsGeneratedMin)
}),
  "error": zod.string().nullish()
})),
  "total": zod.number().min(listIngestionRunsResponseTotalMin),
  "page": zod.number().min(1),
  "page_size": zod.number().min(1).max(listIngestionRunsResponsePageSizeMax)
})

/**
 * @summary Queue an ingestion run
 */
export const createIngestionRunBodyMaxArticlesMax = 1000;



export const CreateIngestionRunBody = zod.object({
  "max_articles": zod.number().min(1).max(createIngestionRunBodyMaxArticlesMax)
})

/**
 * @summary Get ingestion run status
 */
export const GetIngestionRunParams = zod.object({
  "run_id": zod.string()
})

export const getIngestionRunResponseStatsArticlesIngestedMin = 0;

export const getIngestionRunResponseStatsArticlesRelevantMin = 0;

export const getIngestionRunResponseStatsIncidentsCreatedMin = 0;

export const getIngestionRunResponseStatsProposalsGeneratedMin = 0;



export const GetIngestionRunResponse = zod.object({
  "id": zod.string(),
  "status": zod.enum(['queued', 'running', 'completed', 'failed']),
  "started_at": zod.string().datetime({}),
  "finished_at": zod.string().datetime({}).nullish(),
  "created_at": zod.string().datetime({}),
  "stats": zod.object({
  "articles_ingested": zod.number().min(getIngestionRunResponseStatsArticlesIngestedMin),
  "articles_relevant": zod.number().min(getIngestionRunResponseStatsArticlesRelevantMin),
  "incidents_created": zod.number().min(getIngestionRunResponseStatsIncidentsCreatedMin),
  "proposals_generated": zod.number().min(getIngestionRunResponseStatsProposalsGeneratedMin)
}),
  "error": zod.string().nullish()
})

/**
 * @summary Get ingestion scheduler status
 */
export const getIngestionStatusResponseLastRunOneStatsArticlesIngestedMin = 0;

export const getIngestionStatusResponseLastRunOneStatsArticlesRelevantMin = 0;

export const getIngestionStatusResponseLastRunOneStatsIncidentsCreatedMin = 0;

export const getIngestionStatusResponseLastRunOneStatsProposalsGeneratedMin = 0;



export const GetIngestionStatusResponse = zod.object({
  "last_run": zod.object({
  "id": zod.string(),
  "status": zod.enum(['queued', 'running', 'completed', 'failed']),
  "started_at": zod.string().datetime({}),
  "finished_at": zod.string().datetime({}).nullish(),
  "created_at": zod.string().datetime({}),
  "stats": zod.object({
  "articles_ingested": zod.number().min(getIngestionStatusResponseLastRunOneStatsArticlesIngestedMin),
  "articles_relevant": zod.number().min(getIngestionStatusResponseLastRunOneStatsArticlesRelevantMin),
  "incidents_created": zod.number().min(getIngestionStatusResponseLastRunOneStatsIncidentsCreatedMin),
  "proposals_generated": zod.number().min(getIngestionStatusResponseLastRunOneStatsProposalsGeneratedMin)
}),
  "error": zod.string().nullish()
}).nullable(),
  "next_scheduled_run_at": zod.string().datetime({}).nullable()
})

