/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  CreateIngestionRunRequest,
  IngestionRun,
  IngestionRunQueuedResponse,
  IngestionStatus,
  InternalServerErrorResponse,
  NotFoundResponse,
  UnprocessableEntityResponse
} from '../model';



  
  
  
/**
 * @summary Queue an ingestion run
 */
export type createIngestionRunResponse202 = {
  data: IngestionRunQueuedResponse
  status: 202
}

export type createIngestionRunResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createIngestionRunResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type createIngestionRunResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createIngestionRunResponseSuccess = (createIngestionRunResponse202) & {
  headers: Headers;
};
export type createIngestionRunResponseError = (createIngestionRunResponse400 | createIngestionRunResponse422 | createIngestionRunResponse500) & {
  headers: Headers;
};

export type createIngestionRunResponse = (createIngestionRunResponseSuccess | createIngestionRunResponseError)

export const getCreateIngestionRunUrl = () => {


  

  return `http://localhost:5000/ingestion/runs`
}

export const createIngestionRun = async (createIngestionRunRequest: CreateIngestionRunRequest, options?: RequestInit): Promise<createIngestionRunResponse> => {
  
  const res = await fetch(getCreateIngestionRunUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createIngestionRunRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createIngestionRunResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createIngestionRunResponse
}
  



export const getCreateIngestionRunMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateIngestionRunRequest }) => {
    return createIngestionRun(arg, options);
  }
}
export const getCreateIngestionRunMutationKey = () => [`http://localhost:5000/ingestion/runs`] as const;

export type CreateIngestionRunMutationResult = NonNullable<Awaited<ReturnType<typeof createIngestionRun>>>

/**
 * @summary Queue an ingestion run
 */
export const useCreateIngestionRun = <TError = Promise<BadRequestResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createIngestionRun>>, TError, Key, CreateIngestionRunRequest, Awaited<ReturnType<typeof createIngestionRun>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateIngestionRunMutationKey();
  const swrFn = getCreateIngestionRunMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get ingestion run status
 */
export type getIngestionRunResponse200 = {
  data: IngestionRun
  status: 200
}

export type getIngestionRunResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getIngestionRunResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getIngestionRunResponseSuccess = (getIngestionRunResponse200) & {
  headers: Headers;
};
export type getIngestionRunResponseError = (getIngestionRunResponse404 | getIngestionRunResponse500) & {
  headers: Headers;
};

export type getIngestionRunResponse = (getIngestionRunResponseSuccess | getIngestionRunResponseError)

export const getGetIngestionRunUrl = (runId: string,) => {


  

  return `http://localhost:5000/ingestion/runs/${runId}`
}

export const getIngestionRun = async (runId: string, options?: RequestInit): Promise<getIngestionRunResponse> => {
  
  const res = await fetch(getGetIngestionRunUrl(runId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getIngestionRunResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getIngestionRunResponse
}
  



export const getGetIngestionRunKey = (runId: string,) => [`http://localhost:5000/ingestion/runs/${runId}`] as const;

export type GetIngestionRunQueryResult = NonNullable<Awaited<ReturnType<typeof getIngestionRun>>>

/**
 * @summary Get ingestion run status
 */
export const useGetIngestionRun = <TError = Promise<NotFoundResponse | InternalServerErrorResponse>>(
  runId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getIngestionRun>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(runId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetIngestionRunKey(runId) : null);
  const swrFn = () => getIngestionRun(runId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get ingestion scheduler status
 */
export type getIngestionStatusResponse200 = {
  data: IngestionStatus
  status: 200
}

export type getIngestionStatusResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getIngestionStatusResponseSuccess = (getIngestionStatusResponse200) & {
  headers: Headers;
};
export type getIngestionStatusResponseError = (getIngestionStatusResponse500) & {
  headers: Headers;
};

export type getIngestionStatusResponse = (getIngestionStatusResponseSuccess | getIngestionStatusResponseError)

export const getGetIngestionStatusUrl = () => {


  

  return `http://localhost:5000/ingestion/status`
}

export const getIngestionStatus = async ( options?: RequestInit): Promise<getIngestionStatusResponse> => {
  
  const res = await fetch(getGetIngestionStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getIngestionStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getIngestionStatusResponse
}
  



export const getGetIngestionStatusKey = () => [`http://localhost:5000/ingestion/status`] as const;

export type GetIngestionStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getIngestionStatus>>>

/**
 * @summary Get ingestion scheduler status
 */
export const useGetIngestionStatus = <TError = Promise<InternalServerErrorResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getIngestionStatus>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetIngestionStatusKey() : null);
  const swrFn = () => getIngestionStatus(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
