/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List articles
 */
export const listArticlesQueryPageDefault = 1;

export const listArticlesQueryPageSizeDefault = 20;
export const listArticlesQueryPageSizeMax = 100;



export const ListArticlesQueryParams = zod.object({
  "state": zod.enum(['raw', 'enriched', 'irrelevant', 'evaluated', 'proposal_generated']).optional(),
  "relevant": zod.boolean().optional(),
  "page": zod.number().min(1).default(listArticlesQueryPageDefault),
  "page_size": zod.number().min(1).max(listArticlesQueryPageSizeMax).default(listArticlesQueryPageSizeDefault)
})

export const listArticlesResponseTotalMin = 0;


export const listArticlesResponsePageSizeMax = 100;



export const ListArticlesResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "source": zod.string(),
  "source_url": zod.string().url(),
  "headline": zod.string(),
  "body": zod.string(),
  "published_at": zod.string().datetime({}),
  "ingestion_run_id": zod.string(),
  "processing_state": zod.enum(['raw', 'enriched', 'irrelevant', 'evaluated', 'proposal_generated']),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "total": zod.number().min(listArticlesResponseTotalMin),
  "page": zod.number().min(1),
  "page_size": zod.number().min(1).max(listArticlesResponsePageSizeMax)
})

/**
 * @summary Get article by id
 */
export const GetArticleParams = zod.object({
  "article_id": zod.string()
})

export const GetArticleResponse = zod.object({
  "id": zod.string(),
  "source": zod.string(),
  "source_url": zod.string().url(),
  "headline": zod.string(),
  "body": zod.string(),
  "published_at": zod.string().datetime({}),
  "ingestion_run_id": zod.string(),
  "processing_state": zod.enum(['raw', 'enriched', 'irrelevant', 'evaluated', 'proposal_generated']),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Get enrichment for an article
 */
export const GetArticleEnrichmentParams = zod.object({
  "article_id": zod.string()
})

export const getArticleEnrichmentResponseImpactWindowConfidenceMin = 0;
export const getArticleEnrichmentResponseImpactWindowConfidenceMax = 1;

export const getArticleEnrichmentResponseRiskScoreMin = 0;
export const getArticleEnrichmentResponseRiskScoreMax = 100;



export const GetArticleEnrichmentResponse = zod.object({
  "article_id": zod.string(),
  "is_relevant": zod.boolean(),
  "relevance_tags": zod.array(zod.enum(['sku', 'shipment', 'supplier', 'weather', 'geopolitical', 'financial'])),
  "horizon": zod.enum(['short_term', 'long_term']),
  "geo": zod.object({
  "countries": zod.array(zod.string()),
  "ports": zod.array(zod.string()),
  "route_ids": zod.array(zod.string()),
  "lat": zod.number().nullish(),
  "lng": zod.number().nullish()
}),
  "impact_window": zod.object({
  "start_at": zod.string().datetime({}),
  "end_at": zod.string().datetime({}),
  "confidence": zod.number().min(getArticleEnrichmentResponseImpactWindowConfidenceMin).max(getArticleEnrichmentResponseImpactWindowConfidenceMax)
}),
  "matched_entities": zod.object({
  "sku_ids": zod.array(zod.string()),
  "supplier_ids": zod.array(zod.string())
}),
  "risk_score": zod.number().min(getArticleEnrichmentResponseRiskScoreMin).max(getArticleEnrichmentResponseRiskScoreMax),
  "risk_level": zod.enum(['low', 'medium', 'high']),
  "explanation": zod.string()
})

