/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  ArticleProcessingState,
  RelevanceTag,
  RiskLevel
} from '../model';
import type {
  Article,
  ArticleListResponse,
  Enrichment
} from '../model';


export const getListArticlesResponseMock = (overrideResponse: Partial<Extract<ArticleListResponse, object>> = {}): ArticleListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), source: faker.string.alpha({length: {min: 10, max: 20}}), source_url: faker.internet.url(), headline: faker.string.alpha({length: {min: 10, max: 20}}), body: faker.string.alpha({length: {min: 10, max: 20}}), published_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ingestion_run_id: faker.string.alpha({length: {min: 10, max: 20}}), processing_state: faker.helpers.arrayElement(Object.values(ArticleProcessingState)), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})), total: faker.number.int({min: 0}), page: faker.number.int({min: 1}), page_size: faker.number.int({min: 1, max: 100}), ...overrideResponse})

export const getGetArticleResponseMock = (overrideResponse: Partial<Extract<Article, object>> = {}): Article => ({id: faker.string.alpha({length: {min: 10, max: 20}}), source: faker.string.alpha({length: {min: 10, max: 20}}), source_url: faker.internet.url(), headline: faker.string.alpha({length: {min: 10, max: 20}}), body: faker.string.alpha({length: {min: 10, max: 20}}), published_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ingestion_run_id: faker.string.alpha({length: {min: 10, max: 20}}), processing_state: faker.helpers.arrayElement(Object.values(ArticleProcessingState)), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetArticleEnrichmentResponseMock = (overrideResponse: Partial<Extract<Enrichment, object>> = {}): Enrichment => ({article_id: faker.string.alpha({length: {min: 10, max: 20}}), is_relevant: faker.datatype.boolean(), relevance_tags: faker.helpers.arrayElements(Object.values(RelevanceTag)), horizon: faker.helpers.arrayElement(['short_term','long_term'] as const), geo: {countries: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ports: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), route_ids: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), lat: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), null]), undefined]), lng: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), null]), undefined])}, impact_window: {start_at: faker.date.past().toISOString().slice(0, 19) + 'Z', end_at: faker.date.past().toISOString().slice(0, 19) + 'Z', confidence: faker.number.float({min: 0, max: 1, fractionDigits: 2})}, matched_entities: {sku_ids: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), supplier_ids: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}})))}, risk_score: faker.number.int({min: 0, max: 100}), risk_level: faker.helpers.arrayElement(Object.values(RiskLevel)), explanation: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getListArticlesMockHandler = (overrideResponse?: ArticleListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ArticleListResponse> | ArticleListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/articles', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListArticlesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetArticleMockHandler = (overrideResponse?: Article | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Article> | Article), options?: RequestHandlerOptions) => {
  return http.get('*/articles/:articleId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetArticleResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetArticleEnrichmentMockHandler = (overrideResponse?: Enrichment | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Enrichment> | Enrichment), options?: RequestHandlerOptions) => {
  return http.get('*/articles/:articleId/enrichment', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetArticleEnrichmentResponseMock(),
      { status: 200
      })
  }, options)
}
export const getArticlesMock = () => [
  getListArticlesMockHandler(),
  getGetArticleMockHandler(),
  getGetArticleEnrichmentMockHandler()
]
