/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  Article,
  ArticleListResponse,
  BadRequestResponse,
  Enrichment,
  InternalServerErrorResponse,
  ListArticlesParams,
  NotFoundResponse
} from '../model';



  
  
  
/**
 * @summary List articles
 */
export type listArticlesResponse200 = {
  data: ArticleListResponse
  status: 200
}

export type listArticlesResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type listArticlesResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listArticlesResponseSuccess = (listArticlesResponse200) & {
  headers: Headers;
};
export type listArticlesResponseError = (listArticlesResponse400 | listArticlesResponse500) & {
  headers: Headers;
};

export type listArticlesResponse = (listArticlesResponseSuccess | listArticlesResponseError)

export const getListArticlesUrl = (params?: ListArticlesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/v1/articles?${stringifiedParams}` : `http://localhost:8080/api/v1/articles`
}

export const listArticles = async (params?: ListArticlesParams, options?: RequestInit): Promise<listArticlesResponse> => {
  
  const res = await fetch(getListArticlesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listArticlesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listArticlesResponse
}
  



export const getListArticlesKey = (params?: ListArticlesParams,) => [`http://localhost:8080/api/v1/articles`, ...(params ? [params]: [])] as const;

export type ListArticlesQueryResult = NonNullable<Awaited<ReturnType<typeof listArticles>>>

/**
 * @summary List articles
 */
export const useListArticles = <TError = Promise<BadRequestResponse | InternalServerErrorResponse>>(
  params?: ListArticlesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listArticles>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListArticlesKey(params) : null);
  const swrFn = () => listArticles(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get article by id
 */
export type getArticleResponse200 = {
  data: Article
  status: 200
}

export type getArticleResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getArticleResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getArticleResponseSuccess = (getArticleResponse200) & {
  headers: Headers;
};
export type getArticleResponseError = (getArticleResponse404 | getArticleResponse500) & {
  headers: Headers;
};

export type getArticleResponse = (getArticleResponseSuccess | getArticleResponseError)

export const getGetArticleUrl = (articleId: string,) => {


  

  return `http://localhost:8080/api/v1/articles/${articleId}`
}

export const getArticle = async (articleId: string, options?: RequestInit): Promise<getArticleResponse> => {
  
  const res = await fetch(getGetArticleUrl(articleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getArticleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getArticleResponse
}
  



export const getGetArticleKey = (articleId: string,) => [`http://localhost:8080/api/v1/articles/${articleId}`] as const;

export type GetArticleQueryResult = NonNullable<Awaited<ReturnType<typeof getArticle>>>

/**
 * @summary Get article by id
 */
export const useGetArticle = <TError = Promise<NotFoundResponse | InternalServerErrorResponse>>(
  articleId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getArticle>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(articleId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetArticleKey(articleId) : null);
  const swrFn = () => getArticle(articleId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get enrichment for an article
 */
export type getArticleEnrichmentResponse200 = {
  data: Enrichment
  status: 200
}

export type getArticleEnrichmentResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getArticleEnrichmentResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getArticleEnrichmentResponseSuccess = (getArticleEnrichmentResponse200) & {
  headers: Headers;
};
export type getArticleEnrichmentResponseError = (getArticleEnrichmentResponse404 | getArticleEnrichmentResponse500) & {
  headers: Headers;
};

export type getArticleEnrichmentResponse = (getArticleEnrichmentResponseSuccess | getArticleEnrichmentResponseError)

export const getGetArticleEnrichmentUrl = (articleId: string,) => {


  

  return `http://localhost:8080/api/v1/articles/${articleId}/enrichment`
}

export const getArticleEnrichment = async (articleId: string, options?: RequestInit): Promise<getArticleEnrichmentResponse> => {
  
  const res = await fetch(getGetArticleEnrichmentUrl(articleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getArticleEnrichmentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getArticleEnrichmentResponse
}
  



export const getGetArticleEnrichmentKey = (articleId: string,) => [`http://localhost:8080/api/v1/articles/${articleId}/enrichment`] as const;

export type GetArticleEnrichmentQueryResult = NonNullable<Awaited<ReturnType<typeof getArticleEnrichment>>>

/**
 * @summary Get enrichment for an article
 */
export const useGetArticleEnrichment = <TError = Promise<NotFoundResponse | InternalServerErrorResponse>>(
  articleId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getArticleEnrichment>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(articleId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetArticleEnrichmentKey(articleId) : null);
  const swrFn = () => getArticleEnrichment(articleId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
