/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List incidents
 */
export const listIncidentsQueryPageDefault = 1;

export const listIncidentsQueryPageSizeDefault = 20;
export const listIncidentsQueryPageSizeMax = 100;



export const ListIncidentsQueryParams = zod.object({
  "status": zod.enum(['open', 'monitoring', 'awaiting_decision', 'resolved', 'dismissed']).optional(),
  "classification": zod.enum(['risk_exposure', 'active_disruption']).optional(),
  "risk_level": zod.enum(['low', 'medium', 'high']).optional(),
  "page": zod.number().min(1).default(listIncidentsQueryPageDefault),
  "page_size": zod.number().min(1).max(listIncidentsQueryPageSizeMax).default(listIncidentsQueryPageSizeDefault)
})

export const listIncidentsResponseItemsItemRiskScoreMin = -1;
export const listIncidentsResponseItemsItemRiskScoreMax = 100;

export const listIncidentsResponseTotalMin = 0;


export const listIncidentsResponsePageSizeMax = 100;



export const ListIncidentsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "article_id": zod.string(),
  "classification": zod.enum(['risk_exposure', 'active_disruption']),
  "status": zod.enum(['open', 'monitoring', 'awaiting_decision', 'resolved', 'dismissed']),
  "reasoning": zod.string(),
  "overlap_tags": zod.array(zod.enum(['port_overlap', 'route_overlap', 'immediate_sku_threat'])),
  "risk_score": zod.number().min(listIncidentsResponseItemsItemRiskScoreMin).max(listIncidentsResponseItemsItemRiskScoreMax),
  "risk_level": zod.enum(['low', 'medium', 'high']),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "total": zod.number().min(listIncidentsResponseTotalMin),
  "page": zod.number().min(1),
  "page_size": zod.number().min(1).max(listIncidentsResponsePageSizeMax)
})

/**
 * @summary Get incident by id
 */
export const GetIncidentParams = zod.object({
  "incident_id": zod.string()
})

export const getIncidentResponseRiskScoreMin = -1;
export const getIncidentResponseRiskScoreMax = 100;



export const GetIncidentResponse = zod.object({
  "id": zod.string(),
  "article_id": zod.string(),
  "classification": zod.enum(['risk_exposure', 'active_disruption']),
  "status": zod.enum(['open', 'monitoring', 'awaiting_decision', 'resolved', 'dismissed']),
  "reasoning": zod.string(),
  "overlap_tags": zod.array(zod.enum(['port_overlap', 'route_overlap', 'immediate_sku_threat'])),
  "risk_score": zod.number().min(getIncidentResponseRiskScoreMin).max(getIncidentResponseRiskScoreMax),
  "risk_level": zod.enum(['low', 'medium', 'high']),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

