/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  IncidentClassification,
  IncidentStatus,
  OverlapTag,
  RiskLevel
} from '../model';
import type {
  Incident,
  IncidentListResponse
} from '../model';


export const getListIncidentsResponseMock = (overrideResponse: Partial<Extract<IncidentListResponse, object>> = {}): IncidentListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), article_id: faker.string.alpha({length: {min: 10, max: 20}}), classification: faker.helpers.arrayElement(Object.values(IncidentClassification)), status: faker.helpers.arrayElement(Object.values(IncidentStatus)), reasoning: faker.string.alpha({length: {min: 10, max: 20}}), overlap_tags: faker.helpers.arrayElements(Object.values(OverlapTag)), risk_score: faker.number.int({min: -1, max: 100}), risk_level: faker.helpers.arrayElement(Object.values(RiskLevel)), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})), total: faker.number.int({min: 0}), page: faker.number.int({min: 1}), page_size: faker.number.int({min: 1, max: 100}), ...overrideResponse})

export const getGetIncidentResponseMock = (overrideResponse: Partial<Extract<Incident, object>> = {}): Incident => ({id: faker.string.alpha({length: {min: 10, max: 20}}), article_id: faker.string.alpha({length: {min: 10, max: 20}}), classification: faker.helpers.arrayElement(Object.values(IncidentClassification)), status: faker.helpers.arrayElement(Object.values(IncidentStatus)), reasoning: faker.string.alpha({length: {min: 10, max: 20}}), overlap_tags: faker.helpers.arrayElements(Object.values(OverlapTag)), risk_score: faker.number.int({min: -1, max: 100}), risk_level: faker.helpers.arrayElement(Object.values(RiskLevel)), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})


export const getListIncidentsMockHandler = (overrideResponse?: IncidentListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<IncidentListResponse> | IncidentListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/incidents', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListIncidentsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetIncidentMockHandler = (overrideResponse?: Incident | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Incident> | Incident), options?: RequestHandlerOptions) => {
  return http.get('*/incidents/:incidentId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetIncidentResponseMock(),
      { status: 200
      })
  }, options)
}
export const getIncidentsMock = () => [
  getListIncidentsMockHandler(),
  getGetIncidentMockHandler()
]
