/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  BadRequestResponse,
  Incident,
  IncidentListResponse,
  InternalServerErrorResponse,
  ListIncidentsParams,
  NotFoundResponse
} from '../model';



  
  
  
/**
 * @summary List incidents
 */
export type listIncidentsResponse200 = {
  data: IncidentListResponse
  status: 200
}

export type listIncidentsResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type listIncidentsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listIncidentsResponseSuccess = (listIncidentsResponse200) & {
  headers: Headers;
};
export type listIncidentsResponseError = (listIncidentsResponse400 | listIncidentsResponse500) & {
  headers: Headers;
};

export type listIncidentsResponse = (listIncidentsResponseSuccess | listIncidentsResponseError)

export const getListIncidentsUrl = (params?: ListIncidentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/incidents?${stringifiedParams}` : `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/incidents`
}

export const listIncidents = async (params?: ListIncidentsParams, options?: RequestInit): Promise<listIncidentsResponse> => {
  
  const res = await fetch(getListIncidentsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listIncidentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listIncidentsResponse
}
  



export const getListIncidentsKey = (params?: ListIncidentsParams,) => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/incidents`, ...(params ? [params]: [])] as const;

export type ListIncidentsQueryResult = NonNullable<Awaited<ReturnType<typeof listIncidents>>>

/**
 * @summary List incidents
 */
export const useListIncidents = <TError = Promise<BadRequestResponse | InternalServerErrorResponse>>(
  params?: ListIncidentsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listIncidents>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListIncidentsKey(params) : null);
  const swrFn = () => listIncidents(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get incident by id
 */
export type getIncidentResponse200 = {
  data: Incident
  status: 200
}

export type getIncidentResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getIncidentResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getIncidentResponseSuccess = (getIncidentResponse200) & {
  headers: Headers;
};
export type getIncidentResponseError = (getIncidentResponse404 | getIncidentResponse500) & {
  headers: Headers;
};

export type getIncidentResponse = (getIncidentResponseSuccess | getIncidentResponseError)

export const getGetIncidentUrl = (incidentId: string,) => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/incidents/${incidentId}`
}

export const getIncident = async (incidentId: string, options?: RequestInit): Promise<getIncidentResponse> => {
  
  const res = await fetch(getGetIncidentUrl(incidentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getIncidentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getIncidentResponse
}
  



export const getGetIncidentKey = (incidentId: string,) => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/incidents/${incidentId}`] as const;

export type GetIncidentQueryResult = NonNullable<Awaited<ReturnType<typeof getIncident>>>

/**
 * @summary Get incident by id
 */
export const useGetIncident = <TError = Promise<NotFoundResponse | InternalServerErrorResponse>>(
  incidentId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getIncident>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(incidentId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetIncidentKey(incidentId) : null);
  const swrFn = () => getIncident(incidentId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
