/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  RiskLevel
} from '../model';
import type {
  CompanyProfile,
  RiskProfile
} from '../model';


export const getGetCompanyProfileResponseMock = (overrideResponse: Partial<Extract<CompanyProfile, object>> = {}): CompanyProfile => ({autonomy_enabled: faker.datatype.boolean(), max_auto_risk_level: faker.helpers.arrayElement(Object.values(RiskLevel)), disallowed_categories: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getUpdateCompanyProfileResponseMock = (overrideResponse: Partial<Extract<CompanyProfile, object>> = {}): CompanyProfile => ({autonomy_enabled: faker.datatype.boolean(), max_auto_risk_level: faker.helpers.arrayElement(Object.values(RiskLevel)), disallowed_categories: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getGetRiskProfileResponseMock = (overrideResponse: Partial<Extract<RiskProfile, object>> = {}): RiskProfile => ({manager_risk_tolerance_score: faker.number.float({min: 0, max: 1, fractionDigits: 2}), last_updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})


export const getGetCompanyProfileMockHandler = (overrideResponse?: CompanyProfile | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CompanyProfile> | CompanyProfile), options?: RequestHandlerOptions) => {
  return http.get('*/company/profile', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCompanyProfileResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateCompanyProfileMockHandler = (overrideResponse?: CompanyProfile | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CompanyProfile> | CompanyProfile), options?: RequestHandlerOptions) => {
  return http.put('*/company/profile', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateCompanyProfileResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetRiskProfileMockHandler = (overrideResponse?: RiskProfile | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<RiskProfile> | RiskProfile), options?: RequestHandlerOptions) => {
  return http.get('*/config/risk-profile', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetRiskProfileResponseMock(),
      { status: 200
      })
  }, options)
}
export const getCompanyConfigMock = () => [
  getGetCompanyProfileMockHandler(),
  getUpdateCompanyProfileMockHandler(),
  getGetRiskProfileMockHandler()
]
