/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  CompanyProfile,
  InternalServerErrorResponse,
  RiskProfile,
  UnprocessableEntityResponse,
  UpdateCompanyProfileRequest
} from '../model';



  
  
  
/**
 * @summary Get company policy settings
 */
export type getCompanyProfileResponse200 = {
  data: CompanyProfile
  status: 200
}

export type getCompanyProfileResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getCompanyProfileResponseSuccess = (getCompanyProfileResponse200) & {
  headers: Headers;
};
export type getCompanyProfileResponseError = (getCompanyProfileResponse500) & {
  headers: Headers;
};

export type getCompanyProfileResponse = (getCompanyProfileResponseSuccess | getCompanyProfileResponseError)

export const getGetCompanyProfileUrl = () => {


  

  return `http://localhost:8080/api/v1/company/profile`
}

export const getCompanyProfile = async ( options?: RequestInit): Promise<getCompanyProfileResponse> => {
  
  const res = await fetch(getGetCompanyProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCompanyProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCompanyProfileResponse
}
  



export const getGetCompanyProfileKey = () => [`http://localhost:8080/api/v1/company/profile`] as const;

export type GetCompanyProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getCompanyProfile>>>

/**
 * @summary Get company policy settings
 */
export const useGetCompanyProfile = <TError = Promise<InternalServerErrorResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCompanyProfile>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCompanyProfileKey() : null);
  const swrFn = () => getCompanyProfile(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update company policy settings
 */
export type updateCompanyProfileResponse200 = {
  data: CompanyProfile
  status: 200
}

export type updateCompanyProfileResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateCompanyProfileResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type updateCompanyProfileResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateCompanyProfileResponseSuccess = (updateCompanyProfileResponse200) & {
  headers: Headers;
};
export type updateCompanyProfileResponseError = (updateCompanyProfileResponse400 | updateCompanyProfileResponse422 | updateCompanyProfileResponse500) & {
  headers: Headers;
};

export type updateCompanyProfileResponse = (updateCompanyProfileResponseSuccess | updateCompanyProfileResponseError)

export const getUpdateCompanyProfileUrl = () => {


  

  return `http://localhost:8080/api/v1/company/profile`
}

export const updateCompanyProfile = async (updateCompanyProfileRequest: UpdateCompanyProfileRequest, options?: RequestInit): Promise<updateCompanyProfileResponse> => {
  
  const res = await fetch(getUpdateCompanyProfileUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCompanyProfileRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateCompanyProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateCompanyProfileResponse
}
  



export const getUpdateCompanyProfileMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateCompanyProfileRequest }) => {
    return updateCompanyProfile(arg, options);
  }
}
export const getUpdateCompanyProfileMutationKey = () => [`http://localhost:8080/api/v1/company/profile`] as const;

export type UpdateCompanyProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateCompanyProfile>>>

/**
 * @summary Update company policy settings
 */
export const useUpdateCompanyProfile = <TError = Promise<BadRequestResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateCompanyProfile>>, TError, Key, UpdateCompanyProfileRequest, Awaited<ReturnType<typeof updateCompanyProfile>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateCompanyProfileMutationKey();
  const swrFn = getUpdateCompanyProfileMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get learned manager risk profile
 */
export type getRiskProfileResponse200 = {
  data: RiskProfile
  status: 200
}

export type getRiskProfileResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getRiskProfileResponseSuccess = (getRiskProfileResponse200) & {
  headers: Headers;
};
export type getRiskProfileResponseError = (getRiskProfileResponse500) & {
  headers: Headers;
};

export type getRiskProfileResponse = (getRiskProfileResponseSuccess | getRiskProfileResponseError)

export const getGetRiskProfileUrl = () => {


  

  return `http://localhost:8080/api/v1/config/risk-profile`
}

export const getRiskProfile = async ( options?: RequestInit): Promise<getRiskProfileResponse> => {
  
  const res = await fetch(getGetRiskProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getRiskProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRiskProfileResponse
}
  



export const getGetRiskProfileKey = () => [`http://localhost:8080/api/v1/config/risk-profile`] as const;

export type GetRiskProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getRiskProfile>>>

/**
 * @summary Get learned manager risk profile
 */
export const useGetRiskProfile = <TError = Promise<InternalServerErrorResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getRiskProfile>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetRiskProfileKey() : null);
  const swrFn = () => getRiskProfile(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
