/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Get company policy settings
 */
export const GetCompanyProfileResponse = zod.object({
  "autonomy_enabled": zod.boolean(),
  "max_auto_risk_level": zod.enum(['low', 'medium', 'high']),
  "disallowed_categories": zod.array(zod.string())
})

/**
 * @summary Update company policy settings
 */
export const UpdateCompanyProfileBody = zod.object({
  "autonomy_enabled": zod.boolean(),
  "max_auto_risk_level": zod.enum(['low', 'medium', 'high']),
  "disallowed_categories": zod.array(zod.string())
})

export const UpdateCompanyProfileResponse = zod.object({
  "autonomy_enabled": zod.boolean(),
  "max_auto_risk_level": zod.enum(['low', 'medium', 'high']),
  "disallowed_categories": zod.array(zod.string())
})

/**
 * @summary Get learned manager risk profile
 */
export const getRiskProfileResponseManagerRiskToleranceScoreMin = 0;
export const getRiskProfileResponseManagerRiskToleranceScoreMax = 1;



export const GetRiskProfileResponse = zod.object({
  "manager_risk_tolerance_score": zod.number().min(getRiskProfileResponseManagerRiskToleranceScoreMin).max(getRiskProfileResponseManagerRiskToleranceScoreMax),
  "last_updated_at": zod.string().datetime({})
})

