/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Submit feedback to improve soft risk profile
 */
export const SubmitProposalFeedbackParams = zod.object({
  "proposal_id": zod.string()
})

export const SubmitProposalFeedbackBody = zod.object({
  "accepted": zod.boolean(),
  "override_reason": zod.enum(['too_risky', 'too_conservative', 'other']),
  "notes": zod.string()
})

export const submitProposalFeedbackResponseRiskProfileManagerRiskToleranceScoreMin = 0;
export const submitProposalFeedbackResponseRiskProfileManagerRiskToleranceScoreMax = 1;



export const SubmitProposalFeedbackResponse = zod.object({
  "status": zod.enum(['accepted']),
  "risk_profile": zod.object({
  "manager_risk_tolerance_score": zod.number().min(submitProposalFeedbackResponseRiskProfileManagerRiskToleranceScoreMin).max(submitProposalFeedbackResponseRiskProfileManagerRiskToleranceScoreMax),
  "last_updated_at": zod.string().datetime({})
})
})

