/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ProposalFeedbackResponse
} from '../model';


export const getSubmitProposalFeedbackResponseMock = (overrideResponse: Partial<Extract<ProposalFeedbackResponse, object>> = {}): ProposalFeedbackResponse => ({status: faker.helpers.arrayElement(['accepted'] as const), risk_profile: {manager_risk_tolerance_score: faker.number.float({min: 0, max: 1, fractionDigits: 2}), last_updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'}, ...overrideResponse})


export const getSubmitProposalFeedbackMockHandler = (overrideResponse?: ProposalFeedbackResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ProposalFeedbackResponse> | ProposalFeedbackResponse), options?: RequestHandlerOptions) => {
  return http.post('*/feedback/proposals/:proposalId', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSubmitProposalFeedbackResponseMock(),
      { status: 200
      })
  }, options)
}
export const getFeedbackMock = () => [
  getSubmitProposalFeedbackMockHandler()
]
