/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  InternalServerErrorResponse,
  NotFoundResponse,
  ProposalFeedbackRequest,
  ProposalFeedbackResponse,
  UnprocessableEntityResponse
} from '../model';



  
  
  
/**
 * @summary Submit feedback to improve soft risk profile
 */
export type submitProposalFeedbackResponse200 = {
  data: ProposalFeedbackResponse
  status: 200
}

export type submitProposalFeedbackResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type submitProposalFeedbackResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type submitProposalFeedbackResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type submitProposalFeedbackResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type submitProposalFeedbackResponseSuccess = (submitProposalFeedbackResponse200) & {
  headers: Headers;
};
export type submitProposalFeedbackResponseError = (submitProposalFeedbackResponse400 | submitProposalFeedbackResponse404 | submitProposalFeedbackResponse422 | submitProposalFeedbackResponse500) & {
  headers: Headers;
};

export type submitProposalFeedbackResponse = (submitProposalFeedbackResponseSuccess | submitProposalFeedbackResponseError)

export const getSubmitProposalFeedbackUrl = (proposalId: string,) => {


  

  return `http://localhost:5000/feedback/proposals/${proposalId}`
}

export const submitProposalFeedback = async (proposalId: string,
    proposalFeedbackRequest: ProposalFeedbackRequest, options?: RequestInit): Promise<submitProposalFeedbackResponse> => {
  
  const res = await fetch(getSubmitProposalFeedbackUrl(proposalId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      proposalFeedbackRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: submitProposalFeedbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as submitProposalFeedbackResponse
}
  



export const getSubmitProposalFeedbackMutationFetcher = (proposalId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: ProposalFeedbackRequest }) => {
    return submitProposalFeedback(proposalId, arg, options);
  }
}
export const getSubmitProposalFeedbackMutationKey = (proposalId: string,) => [`http://localhost:5000/feedback/proposals/${proposalId}`] as const;

export type SubmitProposalFeedbackMutationResult = NonNullable<Awaited<ReturnType<typeof submitProposalFeedback>>>

/**
 * @summary Submit feedback to improve soft risk profile
 */
export const useSubmitProposalFeedback = <TError = Promise<BadRequestResponse | NotFoundResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
  proposalId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof submitProposalFeedback>>, TError, Key, ProposalFeedbackRequest, Awaited<ReturnType<typeof submitProposalFeedback>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSubmitProposalFeedbackMutationKey(proposalId);
  const swrFn = getSubmitProposalFeedbackMutationFetcher(proposalId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
