/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ActionProposal,
  BadRequestResponse,
  InternalServerErrorResponse,
  NotFoundResponse,
  ProposalDecisionRequest,
  ProposalDecisionResponse,
  ProposalGenerateResponse,
  ProposalListResponse,
  UnprocessableEntityResponse
} from '../model';



  
  
  
/**
 * @summary Generate proposals for an incident
 */
export type generateProposalsResponse202 = {
  data: ProposalGenerateResponse
  status: 202
}

export type generateProposalsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type generateProposalsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type generateProposalsResponseSuccess = (generateProposalsResponse202) & {
  headers: Headers;
};
export type generateProposalsResponseError = (generateProposalsResponse404 | generateProposalsResponse500) & {
  headers: Headers;
};

export type generateProposalsResponse = (generateProposalsResponseSuccess | generateProposalsResponseError)

export const getGenerateProposalsUrl = (incidentId: string,) => {


  

  return `http://localhost:8080/api/v1/incidents/${incidentId}/proposals:generate`
}

export const generateProposals = async (incidentId: string, options?: RequestInit): Promise<generateProposalsResponse> => {
  
  const res = await fetch(getGenerateProposalsUrl(incidentId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: generateProposalsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generateProposalsResponse
}
  



export const getGenerateProposalsMutationFetcher = (incidentId: string, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return generateProposals(incidentId, options);
  }
}
export const getGenerateProposalsMutationKey = (incidentId: string,) => [`http://localhost:8080/api/v1/incidents/${incidentId}/proposals:generate`] as const;

export type GenerateProposalsMutationResult = NonNullable<Awaited<ReturnType<typeof generateProposals>>>

/**
 * @summary Generate proposals for an incident
 */
export const useGenerateProposals = <TError = Promise<NotFoundResponse | InternalServerErrorResponse>>(
  incidentId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof generateProposals>>, TError, Key, Arguments, Awaited<ReturnType<typeof generateProposals>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getGenerateProposalsMutationKey(incidentId);
  const swrFn = getGenerateProposalsMutationFetcher(incidentId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary List proposals for an incident
 */
export type listIncidentProposalsResponse200 = {
  data: ProposalListResponse
  status: 200
}

export type listIncidentProposalsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type listIncidentProposalsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listIncidentProposalsResponseSuccess = (listIncidentProposalsResponse200) & {
  headers: Headers;
};
export type listIncidentProposalsResponseError = (listIncidentProposalsResponse404 | listIncidentProposalsResponse500) & {
  headers: Headers;
};

export type listIncidentProposalsResponse = (listIncidentProposalsResponseSuccess | listIncidentProposalsResponseError)

export const getListIncidentProposalsUrl = (incidentId: string,) => {


  

  return `http://localhost:8080/api/v1/incidents/${incidentId}/proposals`
}

export const listIncidentProposals = async (incidentId: string, options?: RequestInit): Promise<listIncidentProposalsResponse> => {
  
  const res = await fetch(getListIncidentProposalsUrl(incidentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listIncidentProposalsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listIncidentProposalsResponse
}
  



export const getListIncidentProposalsKey = (incidentId: string,) => [`http://localhost:8080/api/v1/incidents/${incidentId}/proposals`] as const;

export type ListIncidentProposalsQueryResult = NonNullable<Awaited<ReturnType<typeof listIncidentProposals>>>

/**
 * @summary List proposals for an incident
 */
export const useListIncidentProposals = <TError = Promise<NotFoundResponse | InternalServerErrorResponse>>(
  incidentId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listIncidentProposals>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(incidentId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListIncidentProposalsKey(incidentId) : null);
  const swrFn = () => listIncidentProposals(incidentId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get proposal by id
 */
export type getProposalResponse200 = {
  data: ActionProposal
  status: 200
}

export type getProposalResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getProposalResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getProposalResponseSuccess = (getProposalResponse200) & {
  headers: Headers;
};
export type getProposalResponseError = (getProposalResponse404 | getProposalResponse500) & {
  headers: Headers;
};

export type getProposalResponse = (getProposalResponseSuccess | getProposalResponseError)

export const getGetProposalUrl = (proposalId: string,) => {


  

  return `http://localhost:8080/api/v1/proposals/${proposalId}`
}

export const getProposal = async (proposalId: string, options?: RequestInit): Promise<getProposalResponse> => {
  
  const res = await fetch(getGetProposalUrl(proposalId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getProposalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProposalResponse
}
  



export const getGetProposalKey = (proposalId: string,) => [`http://localhost:8080/api/v1/proposals/${proposalId}`] as const;

export type GetProposalQueryResult = NonNullable<Awaited<ReturnType<typeof getProposal>>>

/**
 * @summary Get proposal by id
 */
export const useGetProposal = <TError = Promise<NotFoundResponse | InternalServerErrorResponse>>(
  proposalId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getProposal>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(proposalId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetProposalKey(proposalId) : null);
  const swrFn = () => getProposal(proposalId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Submit manager decision for a proposal
 */
export type decideProposalResponse200 = {
  data: ProposalDecisionResponse
  status: 200
}

export type decideProposalResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type decideProposalResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type decideProposalResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type decideProposalResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type decideProposalResponseSuccess = (decideProposalResponse200) & {
  headers: Headers;
};
export type decideProposalResponseError = (decideProposalResponse400 | decideProposalResponse404 | decideProposalResponse422 | decideProposalResponse500) & {
  headers: Headers;
};

export type decideProposalResponse = (decideProposalResponseSuccess | decideProposalResponseError)

export const getDecideProposalUrl = (proposalId: string,) => {


  

  return `http://localhost:8080/api/v1/proposals/${proposalId}/decision`
}

export const decideProposal = async (proposalId: string,
    proposalDecisionRequest: ProposalDecisionRequest, options?: RequestInit): Promise<decideProposalResponse> => {
  
  const res = await fetch(getDecideProposalUrl(proposalId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      proposalDecisionRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: decideProposalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as decideProposalResponse
}
  



export const getDecideProposalMutationFetcher = (proposalId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: ProposalDecisionRequest }) => {
    return decideProposal(proposalId, arg, options);
  }
}
export const getDecideProposalMutationKey = (proposalId: string,) => [`http://localhost:8080/api/v1/proposals/${proposalId}/decision`] as const;

export type DecideProposalMutationResult = NonNullable<Awaited<ReturnType<typeof decideProposal>>>

/**
 * @summary Submit manager decision for a proposal
 */
export const useDecideProposal = <TError = Promise<BadRequestResponse | NotFoundResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
  proposalId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof decideProposal>>, TError, Key, ProposalDecisionRequest, Awaited<ReturnType<typeof decideProposal>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDecideProposalMutationKey(proposalId);
  const swrFn = getDecideProposalMutationFetcher(proposalId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
