/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  AutonomyIneligibilityReason,
  IncidentStatus,
  ProposalStatus,
  RiskLevel,
  StepCategory,
  StepType
} from '../model';
import type {
  ActionProposal,
  ProposalDecisionResponse,
  ProposalGenerateResponse,
  ProposalListResponse
} from '../model';


export const getGenerateProposalsResponseMock = (overrideResponse: Partial<Extract<ProposalGenerateResponse, object>> = {}): ProposalGenerateResponse => ({incident_id: faker.string.alpha({length: {min: 10, max: 20}}), proposal_ids: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getListIncidentProposalsResponseMock = (overrideResponse: Partial<Extract<ProposalListResponse, object>> = {}): ProposalListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), incident_id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), summary: faker.string.alpha({length: {min: 10, max: 20}}), overall_risk: faker.helpers.arrayElement(Object.values(RiskLevel)), estimated_impact: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(ProposalStatus)), autonomy_eligibility: {auto_eligible: faker.datatype.boolean(), reason: faker.helpers.arrayElement(Object.values(AutonomyIneligibilityReason))}, steps: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), step_type: faker.helpers.arrayElement(Object.values(StepType)), category: faker.helpers.arrayElement(Object.values(StepCategory)), description: faker.string.alpha({length: {min: 10, max: 20}}), requires_human_review: faker.datatype.boolean(), suggested_payload: {}})), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})), total: faker.number.int({min: 0}), page: faker.number.int({min: 1}), page_size: faker.number.int({min: 1, max: 100}), ...overrideResponse})

export const getGetProposalResponseMock = (overrideResponse: Partial<Extract<ActionProposal, object>> = {}): ActionProposal => ({id: faker.string.alpha({length: {min: 10, max: 20}}), incident_id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), summary: faker.string.alpha({length: {min: 10, max: 20}}), overall_risk: faker.helpers.arrayElement(Object.values(RiskLevel)), estimated_impact: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(ProposalStatus)), autonomy_eligibility: {auto_eligible: faker.datatype.boolean(), reason: faker.helpers.arrayElement(Object.values(AutonomyIneligibilityReason))}, steps: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), step_type: faker.helpers.arrayElement(Object.values(StepType)), category: faker.helpers.arrayElement(Object.values(StepCategory)), description: faker.string.alpha({length: {min: 10, max: 20}}), requires_human_review: faker.datatype.boolean(), suggested_payload: {}})), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getDecideProposalResponseMock = (overrideResponse: Partial<Extract<ProposalDecisionResponse, object>> = {}): ProposalDecisionResponse => ({proposal: {id: faker.string.alpha({length: {min: 10, max: 20}}), incident_id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), summary: faker.string.alpha({length: {min: 10, max: 20}}), overall_risk: faker.helpers.arrayElement(Object.values(RiskLevel)), estimated_impact: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(ProposalStatus)), autonomy_eligibility: {auto_eligible: faker.datatype.boolean(), reason: faker.helpers.arrayElement(Object.values(AutonomyIneligibilityReason))}, steps: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), step_type: faker.helpers.arrayElement(Object.values(StepType)), category: faker.helpers.arrayElement(Object.values(StepCategory)), description: faker.string.alpha({length: {min: 10, max: 20}}), requires_human_review: faker.datatype.boolean(), suggested_payload: {}})), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'}, incident_status: faker.helpers.arrayElement(Object.values(IncidentStatus)), ...overrideResponse})


export const getGenerateProposalsMockHandler = (overrideResponse?: ProposalGenerateResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ProposalGenerateResponse> | ProposalGenerateResponse), options?: RequestHandlerOptions) => {
  return http.post('*/incidents/:incidentId/proposals\:generate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGenerateProposalsResponseMock(),
      { status: 202
      })
  }, options)
}

export const getListIncidentProposalsMockHandler = (overrideResponse?: ProposalListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProposalListResponse> | ProposalListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/incidents/:incidentId/proposals', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListIncidentProposalsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetProposalMockHandler = (overrideResponse?: ActionProposal | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ActionProposal> | ActionProposal), options?: RequestHandlerOptions) => {
  return http.get('*/proposals/:proposalId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProposalResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDecideProposalMockHandler = (overrideResponse?: ProposalDecisionResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ProposalDecisionResponse> | ProposalDecisionResponse), options?: RequestHandlerOptions) => {
  return http.post('*/proposals/:proposalId/decision', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDecideProposalResponseMock(),
      { status: 200
      })
  }, options)
}
export const getProposalsMock = () => [
  getGenerateProposalsMockHandler(),
  getListIncidentProposalsMockHandler(),
  getGetProposalMockHandler(),
  getDecideProposalMockHandler()
]
