/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Generate proposals for an incident
 */
export const GenerateProposalsParams = zod.object({
  "incident_id": zod.string()
})

/**
 * @summary List proposals for an incident
 */
export const ListIncidentProposalsParams = zod.object({
  "incident_id": zod.string()
})


export const listIncidentProposalsResponseTotalMin = 0;


export const listIncidentProposalsResponsePageSizeMax = 100;



export const ListIncidentProposalsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "incident_id": zod.string(),
  "title": zod.string(),
  "summary": zod.string(),
  "overall_risk": zod.enum(['low', 'medium', 'high']),
  "estimated_impact": zod.string(),
  "status": zod.enum(['proposed', 'approved', 'rejected', 'partially_approved', 'executed_manual']),
  "autonomy_eligibility": zod.object({
  "auto_eligible": zod.boolean(),
  "reason": zod.enum(['risk_above_company_threshold', 'blocked_category', 'autonomy_disabled', 'eligible'])
}),
  "steps": zod.array(zod.object({
  "id": zod.string(),
  "step_type": zod.enum(['autonomous', 'semi_autonomous', 'manual']),
  "category": zod.enum(['email', 'documentation', 'supplier_change', 'shipment_reroute', 'other']),
  "description": zod.string(),
  "requires_human_review": zod.boolean(),
  "suggested_payload": zod.record(zod.string(), zod.unknown())
})).min(1),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "total": zod.number().min(listIncidentProposalsResponseTotalMin),
  "page": zod.number().min(1),
  "page_size": zod.number().min(1).max(listIncidentProposalsResponsePageSizeMax)
})

/**
 * @summary Get proposal by id
 */
export const GetProposalParams = zod.object({
  "proposal_id": zod.string()
})




export const GetProposalResponse = zod.object({
  "id": zod.string(),
  "incident_id": zod.string(),
  "title": zod.string(),
  "summary": zod.string(),
  "overall_risk": zod.enum(['low', 'medium', 'high']),
  "estimated_impact": zod.string(),
  "status": zod.enum(['proposed', 'approved', 'rejected', 'partially_approved', 'executed_manual']),
  "autonomy_eligibility": zod.object({
  "auto_eligible": zod.boolean(),
  "reason": zod.enum(['risk_above_company_threshold', 'blocked_category', 'autonomy_disabled', 'eligible'])
}),
  "steps": zod.array(zod.object({
  "id": zod.string(),
  "step_type": zod.enum(['autonomous', 'semi_autonomous', 'manual']),
  "category": zod.enum(['email', 'documentation', 'supplier_change', 'shipment_reroute', 'other']),
  "description": zod.string(),
  "requires_human_review": zod.boolean(),
  "suggested_payload": zod.record(zod.string(), zod.unknown())
})).min(1),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Submit manager decision for a proposal
 */
export const DecideProposalParams = zod.object({
  "proposal_id": zod.string()
})

export const DecideProposalBody = zod.object({
  "decision": zod.enum(['approve', 'reject', 'partial_approve']),
  "approved_step_ids": zod.array(zod.string()),
  "manager_note": zod.string()
})




export const DecideProposalResponse = zod.object({
  "proposal": zod.object({
  "id": zod.string(),
  "incident_id": zod.string(),
  "title": zod.string(),
  "summary": zod.string(),
  "overall_risk": zod.enum(['low', 'medium', 'high']),
  "estimated_impact": zod.string(),
  "status": zod.enum(['proposed', 'approved', 'rejected', 'partially_approved', 'executed_manual']),
  "autonomy_eligibility": zod.object({
  "auto_eligible": zod.boolean(),
  "reason": zod.enum(['risk_above_company_threshold', 'blocked_category', 'autonomy_disabled', 'eligible'])
}),
  "steps": zod.array(zod.object({
  "id": zod.string(),
  "step_type": zod.enum(['autonomous', 'semi_autonomous', 'manual']),
  "category": zod.enum(['email', 'documentation', 'supplier_change', 'shipment_reroute', 'other']),
  "description": zod.string(),
  "requires_human_review": zod.boolean(),
  "suggested_payload": zod.record(zod.string(), zod.unknown())
})).min(1),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
}),
  "incident_status": zod.enum(['open', 'monitoring', 'awaiting_decision', 'resolved', 'dismissed'])
})

