/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  MasterStatus,
  ShipmentStatus,
  SkuRiskLevel
} from '../model';
import type {
  ReferenceListResponse,
  Shipment,
  ShipmentListResponse,
  Sku,
  SkuListResponse,
  Supplier,
  SupplierListResponse
} from '../model';


export const getListSkusResponseMock = (overrideResponse: Partial<Extract<SkuListResponse, object>> = {}): SkuListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), sku_code: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), unit_of_measure: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(MasterStatus)), risk_score: faker.number.int({min: -1, max: 100}), risk_level: faker.helpers.arrayElement(Object.values(SkuRiskLevel)), required_qty: faker.number.int({min: 0}), category: faker.string.alpha({length: {min: 10, max: 20}}), supplier_ids: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})), total: faker.number.int({min: 0}), ...overrideResponse})

export const getCreateSkuResponseMock = (overrideResponse: Partial<Extract<Sku, object>> = {}): Sku => ({id: faker.string.alpha({length: {min: 10, max: 20}}), sku_code: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), unit_of_measure: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(MasterStatus)), risk_score: faker.number.int({min: -1, max: 100}), risk_level: faker.helpers.arrayElement(Object.values(SkuRiskLevel)), required_qty: faker.number.int({min: 0}), category: faker.string.alpha({length: {min: 10, max: 20}}), supplier_ids: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdateSkuResponseMock = (overrideResponse: Partial<Extract<Sku, object>> = {}): Sku => ({id: faker.string.alpha({length: {min: 10, max: 20}}), sku_code: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), unit_of_measure: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(MasterStatus)), risk_score: faker.number.int({min: -1, max: 100}), risk_level: faker.helpers.arrayElement(Object.values(SkuRiskLevel)), required_qty: faker.number.int({min: 0}), category: faker.string.alpha({length: {min: 10, max: 20}}), supplier_ids: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getListSuppliersResponseMock = (overrideResponse: Partial<Extract<SupplierListResponse, object>> = {}): SupplierListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), supplier_code: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), country: faker.string.alpha({length: {min: 10, max: 20}}), contact_email: faker.internet.email(), status: faker.helpers.arrayElement(Object.values(MasterStatus)), region: faker.string.alpha({length: {min: 10, max: 20}}), risk_rating: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})), total: faker.number.int({min: 0}), ...overrideResponse})

export const getCreateSupplierResponseMock = (overrideResponse: Partial<Extract<Supplier, object>> = {}): Supplier => ({id: faker.string.alpha({length: {min: 10, max: 20}}), supplier_code: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), country: faker.string.alpha({length: {min: 10, max: 20}}), contact_email: faker.internet.email(), status: faker.helpers.arrayElement(Object.values(MasterStatus)), region: faker.string.alpha({length: {min: 10, max: 20}}), risk_rating: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdateSupplierResponseMock = (overrideResponse: Partial<Extract<Supplier, object>> = {}): Supplier => ({id: faker.string.alpha({length: {min: 10, max: 20}}), supplier_code: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), country: faker.string.alpha({length: {min: 10, max: 20}}), contact_email: faker.internet.email(), status: faker.helpers.arrayElement(Object.values(MasterStatus)), region: faker.string.alpha({length: {min: 10, max: 20}}), risk_rating: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getListShipmentsResponseMock = (overrideResponse: Partial<Extract<ShipmentListResponse, object>> = {}): ShipmentListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), shipment_code: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(ShipmentStatus)), origin_port_id: faker.string.alpha({length: {min: 10, max: 20}}), destination_port_id: faker.string.alpha({length: {min: 10, max: 20}}), route_id: faker.string.alpha({length: {min: 10, max: 20}}), supplier_id: faker.string.alpha({length: {min: 10, max: 20}}), skus: {
        [faker.string.alphanumeric(5)]: faker.number.int({min: 1})
      }, carrier: faker.string.alpha({length: {min: 10, max: 20}}), order_date: faker.date.past().toISOString().slice(0, 19) + 'Z', expected_delivery_date: faker.date.past().toISOString().slice(0, 19) + 'Z', events: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), event_time: faker.date.past().toISOString().slice(0, 19) + 'Z', location: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), metadata: faker.helpers.arrayElement([faker.helpers.arrayElement([null,]), undefined])})), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})), total: faker.number.int({min: 0}), ...overrideResponse})

export const getCreateShipmentResponseMock = (overrideResponse: Partial<Extract<Shipment, object>> = {}): Shipment => ({id: faker.string.alpha({length: {min: 10, max: 20}}), shipment_code: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(ShipmentStatus)), origin_port_id: faker.string.alpha({length: {min: 10, max: 20}}), destination_port_id: faker.string.alpha({length: {min: 10, max: 20}}), route_id: faker.string.alpha({length: {min: 10, max: 20}}), supplier_id: faker.string.alpha({length: {min: 10, max: 20}}), skus: {
        [faker.string.alphanumeric(5)]: faker.number.int({min: 1})
      }, carrier: faker.string.alpha({length: {min: 10, max: 20}}), order_date: faker.date.past().toISOString().slice(0, 19) + 'Z', expected_delivery_date: faker.date.past().toISOString().slice(0, 19) + 'Z', events: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), event_time: faker.date.past().toISOString().slice(0, 19) + 'Z', location: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), metadata: faker.helpers.arrayElement([faker.helpers.arrayElement([null,]), undefined])})), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdateShipmentResponseMock = (overrideResponse: Partial<Extract<Shipment, object>> = {}): Shipment => ({id: faker.string.alpha({length: {min: 10, max: 20}}), shipment_code: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(ShipmentStatus)), origin_port_id: faker.string.alpha({length: {min: 10, max: 20}}), destination_port_id: faker.string.alpha({length: {min: 10, max: 20}}), route_id: faker.string.alpha({length: {min: 10, max: 20}}), supplier_id: faker.string.alpha({length: {min: 10, max: 20}}), skus: {
        [faker.string.alphanumeric(5)]: faker.number.int({min: 1})
      }, carrier: faker.string.alpha({length: {min: 10, max: 20}}), order_date: faker.date.past().toISOString().slice(0, 19) + 'Z', expected_delivery_date: faker.date.past().toISOString().slice(0, 19) + 'Z', events: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), event_time: faker.date.past().toISOString().slice(0, 19) + 'Z', location: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), status: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), metadata: faker.helpers.arrayElement([faker.helpers.arrayElement([null,]), undefined])})), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getListPortsResponseMock = (overrideResponse: Partial<Extract<ReferenceListResponse, object>> = {}): ReferenceListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), code: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), metadata: faker.helpers.arrayElement([{}, undefined])})), total: faker.number.int({min: 0}), ...overrideResponse})

export const getListRoutesResponseMock = (overrideResponse: Partial<Extract<ReferenceListResponse, object>> = {}): ReferenceListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}}), code: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), metadata: faker.helpers.arrayElement([{}, undefined])})), total: faker.number.int({min: 0}), ...overrideResponse})


export const getListSkusMockHandler = (overrideResponse?: SkuListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SkuListResponse> | SkuListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/reference/skus', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListSkusResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateSkuMockHandler = (overrideResponse?: Sku | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Sku> | Sku), options?: RequestHandlerOptions) => {
  return http.post('*/reference/skus', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateSkuResponseMock(),
      { status: 201
      })
  }, options)
}

export const getUpdateSkuMockHandler = (overrideResponse?: Sku | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Sku> | Sku), options?: RequestHandlerOptions) => {
  return http.patch('*/reference/skus/:skuId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateSkuResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListSuppliersMockHandler = (overrideResponse?: SupplierListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SupplierListResponse> | SupplierListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/reference/suppliers', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListSuppliersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateSupplierMockHandler = (overrideResponse?: Supplier | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Supplier> | Supplier), options?: RequestHandlerOptions) => {
  return http.post('*/reference/suppliers', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateSupplierResponseMock(),
      { status: 201
      })
  }, options)
}

export const getUpdateSupplierMockHandler = (overrideResponse?: Supplier | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Supplier> | Supplier), options?: RequestHandlerOptions) => {
  return http.patch('*/reference/suppliers/:supplierId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateSupplierResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListShipmentsMockHandler = (overrideResponse?: ShipmentListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ShipmentListResponse> | ShipmentListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/reference/shipments', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListShipmentsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateShipmentMockHandler = (overrideResponse?: Shipment | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Shipment> | Shipment), options?: RequestHandlerOptions) => {
  return http.post('*/reference/shipments', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateShipmentResponseMock(),
      { status: 201
      })
  }, options)
}

export const getUpdateShipmentMockHandler = (overrideResponse?: Shipment | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Shipment> | Shipment), options?: RequestHandlerOptions) => {
  return http.patch('*/reference/shipments/:shipmentId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateShipmentResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListPortsMockHandler = (overrideResponse?: ReferenceListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReferenceListResponse> | ReferenceListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/reference/ports', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListPortsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListRoutesMockHandler = (overrideResponse?: ReferenceListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReferenceListResponse> | ReferenceListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/reference/routes', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListRoutesResponseMock(),
      { status: 200
      })
  }, options)
}
export const getReferenceMock = () => [
  getListSkusMockHandler(),
  getCreateSkuMockHandler(),
  getUpdateSkuMockHandler(),
  getListSuppliersMockHandler(),
  getCreateSupplierMockHandler(),
  getUpdateSupplierMockHandler(),
  getListShipmentsMockHandler(),
  getCreateShipmentMockHandler(),
  getUpdateShipmentMockHandler(),
  getListPortsMockHandler(),
  getListRoutesMockHandler()
]
