/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List SKU reference data
 */
export const listSkusResponseItemsItemRiskScoreMin = -1;
export const listSkusResponseItemsItemRiskScoreMax = 100;

export const listSkusResponseItemsItemRequiredQtyMin = 0;

export const listSkusResponseTotalMin = 0;



export const ListSkusResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "sku_code": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "unit_of_measure": zod.string(),
  "status": zod.enum(['active', 'inactive']),
  "risk_score": zod.number().min(listSkusResponseItemsItemRiskScoreMin).max(listSkusResponseItemsItemRiskScoreMax),
  "risk_level": zod.enum(['critical', 'high', 'medium', 'low']),
  "required_qty": zod.number().min(listSkusResponseItemsItemRequiredQtyMin),
  "category": zod.string(),
  "supplier_ids": zod.array(zod.string()),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "total": zod.number().min(listSkusResponseTotalMin)
})

/**
 * @summary Create SKU reference record
 */
export const createSkuBodyRiskScoreMin = -1;
export const createSkuBodyRiskScoreMax = 100;

export const createSkuBodyRequiredQtyMin = 0;



export const CreateSkuBody = zod.object({
  "sku_code": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "unit_of_measure": zod.string(),
  "status": zod.enum(['active', 'inactive']),
  "risk_score": zod.number().min(createSkuBodyRiskScoreMin).max(createSkuBodyRiskScoreMax),
  "risk_level": zod.enum(['critical', 'high', 'medium', 'low']),
  "required_qty": zod.number().min(createSkuBodyRequiredQtyMin),
  "category": zod.string(),
  "supplier_ids": zod.array(zod.string())
})

/**
 * @summary Update SKU reference record
 */
export const UpdateSkuParams = zod.object({
  "sku_id": zod.string()
})

export const updateSkuBodyRiskScoreMin = -1;
export const updateSkuBodyRiskScoreMax = 100;

export const updateSkuBodyRequiredQtyMin = 0;



export const UpdateSkuBody = zod.object({
  "sku_code": zod.string().optional(),
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "unit_of_measure": zod.string().optional(),
  "status": zod.enum(['active', 'inactive']).optional(),
  "risk_score": zod.number().min(updateSkuBodyRiskScoreMin).max(updateSkuBodyRiskScoreMax).optional(),
  "risk_level": zod.enum(['critical', 'high', 'medium', 'low']).optional(),
  "required_qty": zod.number().min(updateSkuBodyRequiredQtyMin).optional(),
  "category": zod.string().optional(),
  "supplier_ids": zod.array(zod.string()).optional()
})

export const updateSkuResponseRiskScoreMin = -1;
export const updateSkuResponseRiskScoreMax = 100;

export const updateSkuResponseRequiredQtyMin = 0;



export const UpdateSkuResponse = zod.object({
  "id": zod.string(),
  "sku_code": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "unit_of_measure": zod.string(),
  "status": zod.enum(['active', 'inactive']),
  "risk_score": zod.number().min(updateSkuResponseRiskScoreMin).max(updateSkuResponseRiskScoreMax),
  "risk_level": zod.enum(['critical', 'high', 'medium', 'low']),
  "required_qty": zod.number().min(updateSkuResponseRequiredQtyMin),
  "category": zod.string(),
  "supplier_ids": zod.array(zod.string()),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary List supplier reference data
 */
export const listSuppliersResponseTotalMin = 0;



export const ListSuppliersResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "supplier_code": zod.string(),
  "name": zod.string(),
  "country": zod.string(),
  "contact_email": zod.string().email(),
  "status": zod.enum(['active', 'inactive']),
  "region": zod.string(),
  "risk_rating": zod.string(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "total": zod.number().min(listSuppliersResponseTotalMin)
})

/**
 * @summary Create supplier reference record
 */
export const CreateSupplierBody = zod.object({
  "supplier_code": zod.string(),
  "name": zod.string(),
  "country": zod.string(),
  "contact_email": zod.string().email(),
  "status": zod.enum(['active', 'inactive']),
  "region": zod.string(),
  "risk_rating": zod.string()
})

/**
 * @summary Update supplier reference record
 */
export const UpdateSupplierParams = zod.object({
  "supplier_id": zod.string()
})

export const UpdateSupplierBody = zod.object({
  "supplier_code": zod.string().optional(),
  "name": zod.string().optional(),
  "country": zod.string().optional(),
  "contact_email": zod.string().email().optional(),
  "status": zod.enum(['active', 'inactive']).optional(),
  "region": zod.string().optional(),
  "risk_rating": zod.string().optional()
})

export const UpdateSupplierResponse = zod.object({
  "id": zod.string(),
  "supplier_code": zod.string(),
  "name": zod.string(),
  "country": zod.string(),
  "contact_email": zod.string().email(),
  "status": zod.enum(['active', 'inactive']),
  "region": zod.string(),
  "risk_rating": zod.string(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary List shipment reference data
 */

export const listShipmentsResponseTotalMin = 0;



export const ListShipmentsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "shipment_code": zod.string(),
  "status": zod.enum(['planned', 'in_transit', 'delayed', 'delivered', 'cancelled']),
  "origin_port_id": zod.string(),
  "destination_port_id": zod.string(),
  "route_id": zod.string(),
  "supplier_id": zod.string(),
  "skus": zod.record(zod.string(), zod.number().min(1)).describe('Map of sku_id to quantity required'),
  "carrier": zod.string(),
  "order_date": zod.string().datetime({}),
  "expected_delivery_date": zod.string().datetime({}),
  "events": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "description": zod.string(),
  "event_time": zod.string().datetime({}),
  "location": zod.string().nullish(),
  "status": zod.string().nullish(),
  "metadata": zod.record(zod.string(), zod.unknown()).nullish()
})),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "total": zod.number().min(listShipmentsResponseTotalMin)
})

/**
 * @summary Create shipment reference record
 */



export const CreateShipmentBody = zod.object({
  "shipment_code": zod.string(),
  "status": zod.enum(['planned', 'in_transit', 'delayed', 'delivered', 'cancelled']),
  "origin_port_id": zod.string(),
  "destination_port_id": zod.string(),
  "route_id": zod.string(),
  "supplier_id": zod.string(),
  "skus": zod.record(zod.string(), zod.number().min(1)).describe('Map of sku_id to quantity required'),
  "carrier": zod.string(),
  "order_date": zod.string().datetime({}),
  "expected_delivery_date": zod.string().datetime({}),
  "events": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "description": zod.string(),
  "event_time": zod.string().datetime({}),
  "location": zod.string().nullish(),
  "status": zod.string().nullish(),
  "metadata": zod.record(zod.string(), zod.unknown()).nullish()
}))
})

/**
 * @summary Update shipment reference record
 */
export const UpdateShipmentParams = zod.object({
  "shipment_id": zod.string()
})




export const UpdateShipmentBody = zod.object({
  "shipment_code": zod.string().optional(),
  "status": zod.enum(['planned', 'in_transit', 'delayed', 'delivered', 'cancelled']).optional(),
  "origin_port_id": zod.string().optional(),
  "destination_port_id": zod.string().optional(),
  "route_id": zod.string().optional(),
  "supplier_id": zod.string().optional(),
  "skus": zod.record(zod.string(), zod.number().min(1)).optional().describe('Map of sku_id to quantity required'),
  "carrier": zod.string().optional(),
  "order_date": zod.string().datetime({}).optional(),
  "expected_delivery_date": zod.string().datetime({}).optional(),
  "events": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "description": zod.string(),
  "event_time": zod.string().datetime({}),
  "location": zod.string().nullish(),
  "status": zod.string().nullish(),
  "metadata": zod.record(zod.string(), zod.unknown()).nullish()
})).optional()
})




export const UpdateShipmentResponse = zod.object({
  "id": zod.string(),
  "shipment_code": zod.string(),
  "status": zod.enum(['planned', 'in_transit', 'delayed', 'delivered', 'cancelled']),
  "origin_port_id": zod.string(),
  "destination_port_id": zod.string(),
  "route_id": zod.string(),
  "supplier_id": zod.string(),
  "skus": zod.record(zod.string(), zod.number().min(1)).describe('Map of sku_id to quantity required'),
  "carrier": zod.string(),
  "order_date": zod.string().datetime({}),
  "expected_delivery_date": zod.string().datetime({}),
  "events": zod.array(zod.object({
  "id": zod.string(),
  "type": zod.string(),
  "description": zod.string(),
  "event_time": zod.string().datetime({}),
  "location": zod.string().nullish(),
  "status": zod.string().nullish(),
  "metadata": zod.record(zod.string(), zod.unknown()).nullish()
})),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary List port reference data
 */
export const listPortsResponseTotalMin = 0;



export const ListPortsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "code": zod.string().nullish(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
})),
  "total": zod.number().min(listPortsResponseTotalMin)
})

/**
 * @summary List route reference data
 */
export const listRoutesResponseTotalMin = 0;



export const ListRoutesResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "code": zod.string().nullish(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
})),
  "total": zod.number().min(listRoutesResponseTotalMin)
})

