/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List SKU reference data
 */
export const listSkusResponseTotalMin = 0;



export const ListSkusResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "sku_code": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "unit_of_measure": zod.string(),
  "status": zod.enum(['active', 'inactive']),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "total": zod.number().min(listSkusResponseTotalMin)
})

/**
 * @summary Create SKU reference record
 */
export const CreateSkuBody = zod.object({
  "sku_code": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "unit_of_measure": zod.string(),
  "status": zod.enum(['active', 'inactive'])
})

/**
 * @summary Update SKU reference record
 */
export const UpdateSkuParams = zod.object({
  "sku_id": zod.string()
})

export const UpdateSkuBody = zod.object({
  "sku_code": zod.string().optional(),
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "unit_of_measure": zod.string().optional(),
  "status": zod.enum(['active', 'inactive']).optional()
})

export const UpdateSkuResponse = zod.object({
  "id": zod.string(),
  "sku_code": zod.string(),
  "name": zod.string(),
  "description": zod.string(),
  "unit_of_measure": zod.string(),
  "status": zod.enum(['active', 'inactive']),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary List supplier reference data
 */
export const listSuppliersResponseTotalMin = 0;



export const ListSuppliersResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "supplier_code": zod.string(),
  "name": zod.string(),
  "country": zod.string(),
  "contact_email": zod.string().email(),
  "status": zod.enum(['active', 'inactive']),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "total": zod.number().min(listSuppliersResponseTotalMin)
})

/**
 * @summary Create supplier reference record
 */
export const CreateSupplierBody = zod.object({
  "supplier_code": zod.string(),
  "name": zod.string(),
  "country": zod.string(),
  "contact_email": zod.string().email(),
  "status": zod.enum(['active', 'inactive'])
})

/**
 * @summary Update supplier reference record
 */
export const UpdateSupplierParams = zod.object({
  "supplier_id": zod.string()
})

export const UpdateSupplierBody = zod.object({
  "supplier_code": zod.string().optional(),
  "name": zod.string().optional(),
  "country": zod.string().optional(),
  "contact_email": zod.string().email().optional(),
  "status": zod.enum(['active', 'inactive']).optional()
})

export const UpdateSupplierResponse = zod.object({
  "id": zod.string(),
  "supplier_code": zod.string(),
  "name": zod.string(),
  "country": zod.string(),
  "contact_email": zod.string().email(),
  "status": zod.enum(['active', 'inactive']),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary List shipment reference data
 */
export const listShipmentsResponseTotalMin = 0;



export const ListShipmentsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "shipment_code": zod.string(),
  "status": zod.enum(['planned', 'in_transit', 'delayed', 'delivered', 'cancelled']),
  "origin_port_id": zod.string(),
  "destination_port_id": zod.string(),
  "route_id": zod.string(),
  "supplier_id": zod.string(),
  "sku_ids": zod.array(zod.string()),
  "eta": zod.string().datetime({}),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "total": zod.number().min(listShipmentsResponseTotalMin)
})

/**
 * @summary Create shipment reference record
 */
export const CreateShipmentBody = zod.object({
  "shipment_code": zod.string(),
  "status": zod.enum(['planned', 'in_transit', 'delayed', 'delivered', 'cancelled']),
  "origin_port_id": zod.string(),
  "destination_port_id": zod.string(),
  "route_id": zod.string(),
  "supplier_id": zod.string(),
  "sku_ids": zod.array(zod.string()),
  "eta": zod.string().datetime({})
})

/**
 * @summary Update shipment reference record
 */
export const UpdateShipmentParams = zod.object({
  "shipment_id": zod.string()
})

export const UpdateShipmentBody = zod.object({
  "shipment_code": zod.string().optional(),
  "status": zod.enum(['planned', 'in_transit', 'delayed', 'delivered', 'cancelled']).optional(),
  "origin_port_id": zod.string().optional(),
  "destination_port_id": zod.string().optional(),
  "route_id": zod.string().optional(),
  "supplier_id": zod.string().optional(),
  "sku_ids": zod.array(zod.string()).optional(),
  "eta": zod.string().datetime({}).optional()
})

export const UpdateShipmentResponse = zod.object({
  "id": zod.string(),
  "shipment_code": zod.string(),
  "status": zod.enum(['planned', 'in_transit', 'delayed', 'delivered', 'cancelled']),
  "origin_port_id": zod.string(),
  "destination_port_id": zod.string(),
  "route_id": zod.string(),
  "supplier_id": zod.string(),
  "sku_ids": zod.array(zod.string()),
  "eta": zod.string().datetime({}),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary List port reference data
 */
export const listPortsResponseTotalMin = 0;



export const ListPortsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "code": zod.string().nullish(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
})),
  "total": zod.number().min(listPortsResponseTotalMin)
})

/**
 * @summary List route reference data
 */
export const listRoutesResponseTotalMin = 0;



export const ListRoutesResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "code": zod.string().nullish(),
  "metadata": zod.record(zod.string(), zod.unknown()).optional()
})),
  "total": zod.number().min(listRoutesResponseTotalMin)
})

