/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Shipping Disruption Management API
 * MVP v1 REST API for ACME Inc. to ingest shipping disruption signals, enrich relevance and impact, escalate incidents, and generate action proposals for manager decisioning.
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BadRequestResponse,
  ConflictResponse,
  CreateShipmentRequest,
  CreateSkuRequest,
  CreateSupplierRequest,
  InternalServerErrorResponse,
  NotFoundResponse,
  ReferenceListResponse,
  Shipment,
  ShipmentListResponse,
  Sku,
  SkuListResponse,
  Supplier,
  SupplierListResponse,
  UnprocessableEntityResponse,
  UpdateShipmentRequest,
  UpdateSkuRequest,
  UpdateSupplierRequest
} from '../model';



  
  
  
/**
 * @summary List SKU reference data
 */
export type listSkusResponse200 = {
  data: SkuListResponse
  status: 200
}

export type listSkusResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listSkusResponseSuccess = (listSkusResponse200) & {
  headers: Headers;
};
export type listSkusResponseError = (listSkusResponse500) & {
  headers: Headers;
};

export type listSkusResponse = (listSkusResponseSuccess | listSkusResponseError)

export const getListSkusUrl = () => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/skus`
}

export const listSkus = async ( options?: RequestInit): Promise<listSkusResponse> => {
  
  const res = await fetch(getListSkusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listSkusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listSkusResponse
}
  



export const getListSkusKey = () => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/skus`] as const;

export type ListSkusQueryResult = NonNullable<Awaited<ReturnType<typeof listSkus>>>

/**
 * @summary List SKU reference data
 */
export const useListSkus = <TError = Promise<InternalServerErrorResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listSkus>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListSkusKey() : null);
  const swrFn = () => listSkus(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create SKU reference record
 */
export type createSkuResponse201 = {
  data: Sku
  status: 201
}

export type createSkuResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createSkuResponse409 = {
  data: ConflictResponse
  status: 409
}

export type createSkuResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type createSkuResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createSkuResponseSuccess = (createSkuResponse201) & {
  headers: Headers;
};
export type createSkuResponseError = (createSkuResponse400 | createSkuResponse409 | createSkuResponse422 | createSkuResponse500) & {
  headers: Headers;
};

export type createSkuResponse = (createSkuResponseSuccess | createSkuResponseError)

export const getCreateSkuUrl = () => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/skus`
}

export const createSku = async (createSkuRequest: CreateSkuRequest, options?: RequestInit): Promise<createSkuResponse> => {
  
  const res = await fetch(getCreateSkuUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSkuRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createSkuResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createSkuResponse
}
  



export const getCreateSkuMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateSkuRequest }) => {
    return createSku(arg, options);
  }
}
export const getCreateSkuMutationKey = () => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/skus`] as const;

export type CreateSkuMutationResult = NonNullable<Awaited<ReturnType<typeof createSku>>>

/**
 * @summary Create SKU reference record
 */
export const useCreateSku = <TError = Promise<BadRequestResponse | ConflictResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createSku>>, TError, Key, CreateSkuRequest, Awaited<ReturnType<typeof createSku>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateSkuMutationKey();
  const swrFn = getCreateSkuMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update SKU reference record
 */
export type updateSkuResponse200 = {
  data: Sku
  status: 200
}

export type updateSkuResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateSkuResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateSkuResponse409 = {
  data: ConflictResponse
  status: 409
}

export type updateSkuResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type updateSkuResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateSkuResponseSuccess = (updateSkuResponse200) & {
  headers: Headers;
};
export type updateSkuResponseError = (updateSkuResponse400 | updateSkuResponse404 | updateSkuResponse409 | updateSkuResponse422 | updateSkuResponse500) & {
  headers: Headers;
};

export type updateSkuResponse = (updateSkuResponseSuccess | updateSkuResponseError)

export const getUpdateSkuUrl = (skuId: string,) => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/skus/${skuId}`
}

export const updateSku = async (skuId: string,
    updateSkuRequest: UpdateSkuRequest, options?: RequestInit): Promise<updateSkuResponse> => {
  
  const res = await fetch(getUpdateSkuUrl(skuId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSkuRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateSkuResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateSkuResponse
}
  



export const getUpdateSkuMutationFetcher = (skuId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateSkuRequest }) => {
    return updateSku(skuId, arg, options);
  }
}
export const getUpdateSkuMutationKey = (skuId: string,) => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/skus/${skuId}`] as const;

export type UpdateSkuMutationResult = NonNullable<Awaited<ReturnType<typeof updateSku>>>

/**
 * @summary Update SKU reference record
 */
export const useUpdateSku = <TError = Promise<BadRequestResponse | NotFoundResponse | ConflictResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
  skuId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateSku>>, TError, Key, UpdateSkuRequest, Awaited<ReturnType<typeof updateSku>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateSkuMutationKey(skuId);
  const swrFn = getUpdateSkuMutationFetcher(skuId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary List supplier reference data
 */
export type listSuppliersResponse200 = {
  data: SupplierListResponse
  status: 200
}

export type listSuppliersResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listSuppliersResponseSuccess = (listSuppliersResponse200) & {
  headers: Headers;
};
export type listSuppliersResponseError = (listSuppliersResponse500) & {
  headers: Headers;
};

export type listSuppliersResponse = (listSuppliersResponseSuccess | listSuppliersResponseError)

export const getListSuppliersUrl = () => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/suppliers`
}

export const listSuppliers = async ( options?: RequestInit): Promise<listSuppliersResponse> => {
  
  const res = await fetch(getListSuppliersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listSuppliersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listSuppliersResponse
}
  



export const getListSuppliersKey = () => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/suppliers`] as const;

export type ListSuppliersQueryResult = NonNullable<Awaited<ReturnType<typeof listSuppliers>>>

/**
 * @summary List supplier reference data
 */
export const useListSuppliers = <TError = Promise<InternalServerErrorResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listSuppliers>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListSuppliersKey() : null);
  const swrFn = () => listSuppliers(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create supplier reference record
 */
export type createSupplierResponse201 = {
  data: Supplier
  status: 201
}

export type createSupplierResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createSupplierResponse409 = {
  data: ConflictResponse
  status: 409
}

export type createSupplierResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type createSupplierResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createSupplierResponseSuccess = (createSupplierResponse201) & {
  headers: Headers;
};
export type createSupplierResponseError = (createSupplierResponse400 | createSupplierResponse409 | createSupplierResponse422 | createSupplierResponse500) & {
  headers: Headers;
};

export type createSupplierResponse = (createSupplierResponseSuccess | createSupplierResponseError)

export const getCreateSupplierUrl = () => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/suppliers`
}

export const createSupplier = async (createSupplierRequest: CreateSupplierRequest, options?: RequestInit): Promise<createSupplierResponse> => {
  
  const res = await fetch(getCreateSupplierUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSupplierRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createSupplierResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createSupplierResponse
}
  



export const getCreateSupplierMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateSupplierRequest }) => {
    return createSupplier(arg, options);
  }
}
export const getCreateSupplierMutationKey = () => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/suppliers`] as const;

export type CreateSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof createSupplier>>>

/**
 * @summary Create supplier reference record
 */
export const useCreateSupplier = <TError = Promise<BadRequestResponse | ConflictResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createSupplier>>, TError, Key, CreateSupplierRequest, Awaited<ReturnType<typeof createSupplier>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateSupplierMutationKey();
  const swrFn = getCreateSupplierMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update supplier reference record
 */
export type updateSupplierResponse200 = {
  data: Supplier
  status: 200
}

export type updateSupplierResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateSupplierResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateSupplierResponse409 = {
  data: ConflictResponse
  status: 409
}

export type updateSupplierResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type updateSupplierResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateSupplierResponseSuccess = (updateSupplierResponse200) & {
  headers: Headers;
};
export type updateSupplierResponseError = (updateSupplierResponse400 | updateSupplierResponse404 | updateSupplierResponse409 | updateSupplierResponse422 | updateSupplierResponse500) & {
  headers: Headers;
};

export type updateSupplierResponse = (updateSupplierResponseSuccess | updateSupplierResponseError)

export const getUpdateSupplierUrl = (supplierId: string,) => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/suppliers/${supplierId}`
}

export const updateSupplier = async (supplierId: string,
    updateSupplierRequest: UpdateSupplierRequest, options?: RequestInit): Promise<updateSupplierResponse> => {
  
  const res = await fetch(getUpdateSupplierUrl(supplierId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSupplierRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateSupplierResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateSupplierResponse
}
  



export const getUpdateSupplierMutationFetcher = (supplierId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateSupplierRequest }) => {
    return updateSupplier(supplierId, arg, options);
  }
}
export const getUpdateSupplierMutationKey = (supplierId: string,) => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/suppliers/${supplierId}`] as const;

export type UpdateSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof updateSupplier>>>

/**
 * @summary Update supplier reference record
 */
export const useUpdateSupplier = <TError = Promise<BadRequestResponse | NotFoundResponse | ConflictResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
  supplierId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateSupplier>>, TError, Key, UpdateSupplierRequest, Awaited<ReturnType<typeof updateSupplier>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateSupplierMutationKey(supplierId);
  const swrFn = getUpdateSupplierMutationFetcher(supplierId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary List shipment reference data
 */
export type listShipmentsResponse200 = {
  data: ShipmentListResponse
  status: 200
}

export type listShipmentsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listShipmentsResponseSuccess = (listShipmentsResponse200) & {
  headers: Headers;
};
export type listShipmentsResponseError = (listShipmentsResponse500) & {
  headers: Headers;
};

export type listShipmentsResponse = (listShipmentsResponseSuccess | listShipmentsResponseError)

export const getListShipmentsUrl = () => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/shipments`
}

export const listShipments = async ( options?: RequestInit): Promise<listShipmentsResponse> => {
  
  const res = await fetch(getListShipmentsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listShipmentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listShipmentsResponse
}
  



export const getListShipmentsKey = () => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/shipments`] as const;

export type ListShipmentsQueryResult = NonNullable<Awaited<ReturnType<typeof listShipments>>>

/**
 * @summary List shipment reference data
 */
export const useListShipments = <TError = Promise<InternalServerErrorResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listShipments>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListShipmentsKey() : null);
  const swrFn = () => listShipments(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Create shipment reference record
 */
export type createShipmentResponse201 = {
  data: Shipment
  status: 201
}

export type createShipmentResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createShipmentResponse409 = {
  data: ConflictResponse
  status: 409
}

export type createShipmentResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type createShipmentResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createShipmentResponseSuccess = (createShipmentResponse201) & {
  headers: Headers;
};
export type createShipmentResponseError = (createShipmentResponse400 | createShipmentResponse409 | createShipmentResponse422 | createShipmentResponse500) & {
  headers: Headers;
};

export type createShipmentResponse = (createShipmentResponseSuccess | createShipmentResponseError)

export const getCreateShipmentUrl = () => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/shipments`
}

export const createShipment = async (createShipmentRequest: CreateShipmentRequest, options?: RequestInit): Promise<createShipmentResponse> => {
  
  const res = await fetch(getCreateShipmentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createShipmentRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createShipmentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createShipmentResponse
}
  



export const getCreateShipmentMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateShipmentRequest }) => {
    return createShipment(arg, options);
  }
}
export const getCreateShipmentMutationKey = () => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/shipments`] as const;

export type CreateShipmentMutationResult = NonNullable<Awaited<ReturnType<typeof createShipment>>>

/**
 * @summary Create shipment reference record
 */
export const useCreateShipment = <TError = Promise<BadRequestResponse | ConflictResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createShipment>>, TError, Key, CreateShipmentRequest, Awaited<ReturnType<typeof createShipment>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateShipmentMutationKey();
  const swrFn = getCreateShipmentMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update shipment reference record
 */
export type updateShipmentResponse200 = {
  data: Shipment
  status: 200
}

export type updateShipmentResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateShipmentResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateShipmentResponse409 = {
  data: ConflictResponse
  status: 409
}

export type updateShipmentResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type updateShipmentResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateShipmentResponseSuccess = (updateShipmentResponse200) & {
  headers: Headers;
};
export type updateShipmentResponseError = (updateShipmentResponse400 | updateShipmentResponse404 | updateShipmentResponse409 | updateShipmentResponse422 | updateShipmentResponse500) & {
  headers: Headers;
};

export type updateShipmentResponse = (updateShipmentResponseSuccess | updateShipmentResponseError)

export const getUpdateShipmentUrl = (shipmentId: string,) => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/shipments/${shipmentId}`
}

export const updateShipment = async (shipmentId: string,
    updateShipmentRequest: UpdateShipmentRequest, options?: RequestInit): Promise<updateShipmentResponse> => {
  
  const res = await fetch(getUpdateShipmentUrl(shipmentId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateShipmentRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateShipmentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateShipmentResponse
}
  



export const getUpdateShipmentMutationFetcher = (shipmentId: string, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateShipmentRequest }) => {
    return updateShipment(shipmentId, arg, options);
  }
}
export const getUpdateShipmentMutationKey = (shipmentId: string,) => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/shipments/${shipmentId}`] as const;

export type UpdateShipmentMutationResult = NonNullable<Awaited<ReturnType<typeof updateShipment>>>

/**
 * @summary Update shipment reference record
 */
export const useUpdateShipment = <TError = Promise<BadRequestResponse | NotFoundResponse | ConflictResponse | UnprocessableEntityResponse | InternalServerErrorResponse>>(
  shipmentId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateShipment>>, TError, Key, UpdateShipmentRequest, Awaited<ReturnType<typeof updateShipment>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateShipmentMutationKey(shipmentId);
  const swrFn = getUpdateShipmentMutationFetcher(shipmentId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary List port reference data
 */
export type listPortsResponse200 = {
  data: ReferenceListResponse
  status: 200
}

export type listPortsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listPortsResponseSuccess = (listPortsResponse200) & {
  headers: Headers;
};
export type listPortsResponseError = (listPortsResponse500) & {
  headers: Headers;
};

export type listPortsResponse = (listPortsResponseSuccess | listPortsResponseError)

export const getListPortsUrl = () => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/ports`
}

export const listPorts = async ( options?: RequestInit): Promise<listPortsResponse> => {
  
  const res = await fetch(getListPortsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listPortsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listPortsResponse
}
  



export const getListPortsKey = () => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/ports`] as const;

export type ListPortsQueryResult = NonNullable<Awaited<ReturnType<typeof listPorts>>>

/**
 * @summary List port reference data
 */
export const useListPorts = <TError = Promise<InternalServerErrorResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listPorts>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListPortsKey() : null);
  const swrFn = () => listPorts(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary List route reference data
 */
export type listRoutesResponse200 = {
  data: ReferenceListResponse
  status: 200
}

export type listRoutesResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type listRoutesResponseSuccess = (listRoutesResponse200) & {
  headers: Headers;
};
export type listRoutesResponseError = (listRoutesResponse500) & {
  headers: Headers;
};

export type listRoutesResponse = (listRoutesResponseSuccess | listRoutesResponseError)

export const getListRoutesUrl = () => {


  

  return `https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/routes`
}

export const listRoutes = async ( options?: RequestInit): Promise<listRoutesResponse> => {
  
  const res = await fetch(getListRoutesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listRoutesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listRoutesResponse
}
  



export const getListRoutesKey = () => [`https://htf2026-backend-4mqbzcv3ya-uc.a.run.app/api/v1/reference/routes`] as const;

export type ListRoutesQueryResult = NonNullable<Awaited<ReturnType<typeof listRoutes>>>

/**
 * @summary List route reference data
 */
export const useListRoutes = <TError = Promise<InternalServerErrorResponse>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listRoutes>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListRoutesKey() : null);
  const swrFn = () => listRoutes(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
